#!/bin/sh
set -e

testPG() {

    lastNumber=`expir ${BUILD_NUMBER} - 1`
    lastTime=`curl -u ${JENKINS_ACCOUNT_USR}:${JENKINS_ACCOUNT_PSW} ${JOB_URL}/${lastNumber}/buildTimestamp`
    today=`date +"%-m/%-d"`
    failure=`curl -u ${JENKINS_ACCOUNT_USR}:${JENKINS_ACCOUNT_PSW} ${JOB_URL}/${lastNumber}/api/xml | grep -c '<result>FAILURE</result>'` || true

    if ( "${lastTime%/*}" -gt "${today}" || failure == "1") ;then
        echo "test pg"
    else
        echo "666666"
    fi
}
